### PR TITLE
Interface update

### PR DESCRIPTION
**Pull request by yasutomo57jp**
I separated some function definitions and implementations into .cpp and .h files.
I also changed the interface to more modern style.

### CODE REVIEW

**Comment by yasutomo57jp** [comment]
I added a small but important bug fix.

**Comment by christofferholmstedt** [comment]
Thanks, I must have missed the email I got from github about this pull request. I will look in to this when I get time, hopefully within 2 weeks.

**Comment by christofferholmstedt** [comment]
Thank you @yasutomo57jp, your changes have now been merged. I would be happy to merge another pull request with your name in the header for all files, the copyright lines.

**Comment by yasutomo57jp** [comment]
Thank you for merging my pull-requests.
OK, I will add my name in the header and send you the pull-request soon.

**Pull request merged**
