### PR TITLE
Update egbis.h

### PR DESCRIPTION
**Pull request by burak-yildizoz**
convert functions should be declared at header file
opencv2/core.hpp is sufficient for cv::Mat definition

### CODE REVIEW

**Review by christofferholmstedt — APPROVED** [review]
Thanks for the improvements in Windows. I don't have access to Windows installation right now so I hope you have tested the changes ;)

**Comment by burak-yildizoz** [comment]
> Thanks for the improvements in Windows. I don't have access to Windows installation right now so I hope you have tested the changes ;)

I have tested with CMake from Git Bash with Microsoft Visual C++ as compiler. When `OpenCV_DIR` is set correct, it works but when the path is incorrect, no helpful error message is shown.

I am surprised that you approved the changes after a long time :)

**Comment by christofferholmstedt** [comment]
@burak-yildizoz I've moved most of my projects to Gitlab instead of Github so not active on Github very often, but should probably login once a month instead of once per quarter so future updates goes faster. :)

**Comment by burak-yildizoz** [comment]
@christofferholmstedt No problem. Thank you for your responsiveness. I would say about the last commit that setting variables in *CMakeLists.txt* is not the best practice and using `-D OpenCV_DIR=path` is better, but since you are okay with updates, I will open a small PR maybe next month :)

**Pull request merged**
